125 placeholder timer
zekehuntergreen/comsem pull request #141
Opened 2022-11-14 01:54 UTC by zambroseo

Added a placeholder timer, bar and text, to the problem page

2022-11-14 02:05 UTC, aedmondson requested changes

2022-11-14 02:05 UTC, aedmondson commented on ComSemApp/templates/ComSemApp/student/assessment.html
> +
insert a \<br> here

2022-11-14 02:05 UTC, aedmondson commented on ComSemApp/templates/ComSemApp/student/assessment.html
> +</script>
Is there a way that we can make the timer bar decrease continuously, rather than ticking each second?

2022-11-15 00:29 UTC, dpmacisaac approved these changes

2022-11-15 00:33 UTC, merged