140 flesh out results page for spoken practice tool
zekehuntergreen/comsem pull request #149
Opened 2022-12-02 19:53 UTC by dpmacisaac

2022-12-02 19:55 UTC, dpmacisaac commented
Noticed there are some issues, Ill have to figure them out before we can merge

2022-12-04 21:17 UTC, aedmondson requested changes

2022-12-04 21:17 UTC, aedmondson commented on ComSemApp/student/views.py
> +from django.views.generic import ListView, DetailView, CreateView, UpdateView, TemplateView, View
View doesn't need to be imported

2022-12-04 21:17 UTC, aedmondson commented on ComSemApp/student/views.py
> +practice_data = [
Mocking this data is good for now. We will change this later

2022-12-04 21:17 UTC, aedmondson commented on ComSemApp/student/views.py
> +        """Get worksheet data for a student in a given course
This docstring needs changed

2022-12-04 21:17 UTC, aedmondson commented on ComSemApp/templates/ComSemApp/student/assessment_results.html
> +                <div class='card-body'> <!--card for displaying results-->
Move comments to line above the line(s) they describe

2022-12-04 21:17 UTC, aedmondson commented on ComSemApp/templates/ComSemApp/student/assessment_results.html
> +										<td>
The indentation in here needs to be made more consistent.

2022-12-04 21:17 UTC, aedmondson commented on ComSemApp/templates/ComSemApp/student/assessment_results.html
> +								$(function(){
Anonymous functions should be declared as arrow functions () => {}

2022-12-04 21:17 UTC, aedmondson commented on ComSemApp/templates/ComSemApp/student/assessment_results.html
> +									$('.show-more').on('click', function(e){
Change the anonymous function to an arrow function (e) =>

2022-12-04 21:26 UTC, aedmondson commented on ComSemApp/templates/ComSemApp/student/assessment_results.html
> +								<th class="text-center invisible"><button class="show-more" type="button">Show More</button></th>
This button class should also include a button style from [Bootstrap](https://getbootstrap.com/docs/4.0/components/buttons/)

2022-12-06 00:43 UTC, Jared-Torii approved these changes

2022-12-06 01:09 UTC, aedmondson approved these changes

2022-12-06 01:09 UTC, merged