143 setup mic start and stop function 1
zekehuntergreen/comsem pull request #170
Opened 2023-01-25 23:19 UTC by dpmacisaac

2023-01-25 23:40 UTC, zambroseo approved these changes
looks good!

2023-01-26 00:25 UTC, aedmondson requested changes

2023-01-26 00:25 UTC, aedmondson commented on ComSemApp/templates/ComSemApp/student/assessment_audio_recording.html
>  			<i class="ti-control-record"></i>
These buttons should be outright deleted instead of hidden

2023-01-26 00:25 UTC, aedmondson commented on ComSemApp/templates/ComSemApp/student/assessment.html
> +<!-- original -->
This should not be referencing original vs reformulation, since we will only be showing originals

2023-01-26 00:25 UTC, aedmondson commented on ComSemApp/templates/ComSemApp/student/assessment.html
> +<!-- original -->
Furthermore, this should be wrapped in a form that points to the url  "{% url 'student:speaking_practice_submit course.id %}".

That form should probably be in a different file to keep things neat. See ComSemApp/templates/ComSemApp/student/attempt_form.html, ComSemApp/templates/ComSemApp/student/expression_list.html (line 38), and the student AttemptCreateView for an example of a form being pulled in from another file and used properly.

2023-01-26 00:25 UTC, aedmondson commented on ComSemApp/templates/ComSemApp/student/assessment.html
> +<!-- Button script for finishing recording. Will need to be changed to call when disabled
Remove commented script

2023-01-26 00:39 UTC, aedmondson commented
Also, just for form submission and audio storage purposes, the Opus recording module uses the var name "audioReformulationBlob" to store its audio blob to sent to the server

2023-01-31 00:07 UTC, aedmondson commented on ComSemApp/templates/ComSemApp/student/assessment_audio_recording.html
>  			<i class="ti-control-record"></i>
This change requires some other refactoring. Handled by #176

2023-01-31 00:08 UTC, aedmondson commented on ComSemApp/templates/ComSemApp/student/assessment.html
> +<!-- original -->
This will be handled in #176

2023-01-31 00:08 UTC, aedmondson approved these changes

2023-02-01 23:36 UTC, merged