161 update problem page to present data in a nicer format
zekehuntergreen/comsem pull request #171
Opened 2023-01-25 23:35 UTC by aedmondson

2023-01-25 23:41 UTC, dpmacisaac requested changes
Pls make timer go down not up ty v mucho

2023-01-25 23:42 UTC, zambroseo reviewed
Timer Count up Need count down

2023-01-26 00:28 UTC, zambroseo approved these changes
timer now counts down, looks good!

2023-01-28 21:34 UTC, Jared-Torii approved these changes
All good for me

2023-01-29 21:33 UTC, merged